[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 1
blur = false

[window.padding]
x = 8
y = 6

[colors.primary]
background = "#0D0F12"
foreground = "#CDD6F4"

[colors.cursor]
cursor = "#F5E0DC"
text = "#11111B"

[colors.selection]
text = "#CDD6F4"
background = "#45475A"

[colors.normal]
black   = "#45475A"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#F5C2E7"
cyan    = "#94E2D5"
white   = "#BAC2DE"

[colors.bright]
black   = "#585B70"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#F5C2E7"
cyan    = "#94E2D5"
white   = "#A6ADC8"
