# Hypridle Configuration

general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid launching multiple instances
    before_sleep_cmd = loginctl lock-session     # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on   # Turn on screen after resume
}

# Dim screen after 5 minutes
listener {
    timeout = 300                                # 5 min
    on-timeout = brightnessctl -s set 10         # Save state & dim
    on-resume = brightnessctl -r                 # Restore brightness
}

# Lock screen after 10 minutes
listener {
    timeout = 600                                # 10 min
    on-timeout = loginctl lock-session           # Lock via systemd
}

# Turn off screen after 15 minutes
listener {
    timeout = 900                                # 15 min
    on-timeout = hyprctl dispatch dpms off       # Screen off
    on-resume = hyprctl dispatch dpms on         # Screen on
}

# Suspend after 30 minutes
listener {
    timeout = 1800                               # 30 min
    on-timeout = systemctl suspend               # Suspend system
}
