# Hyprpaper Wallpaper Configuration

# Set the wallpaper for your monitor(s)
wallpaper {
    monitor = eDP-1
    path = /home/burakt/Pictures/Wallpapers/default.jpg
}

# Disable splash text rendering over the wallpaper
splash = false
