$font = Google Sans

# ------------------------------------------------------------------------------
# GENERAL
# ------------------------------------------------------------------------------
general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = true
}

# ------------------------------------------------------------------------------
# TIME (CLOCK)
# ------------------------------------------------------------------------------
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 80
    font_family = $font Bold
    position = 0, 190
    halign = center
    valign = center
}

# ------------------------------------------------------------------------------
# DATE
# ------------------------------------------------------------------------------
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgba(255, 255, 255, 0.70)
    font_size = 18
    font_family = $font
    position = 0, 120
    halign = center
    valign = center
}

# ------------------------------------------------------------------------------
# INPUT FIELD (Password)
# ------------------------------------------------------------------------------
input-field {
    monitor =
    size = 230, 48 
    outer_color = rgba(255, 255, 255, 0.20)
    inner_color = rgba(15, 15, 20, 0.35)
    font_color = rgba(255, 255, 255, 0.90)
    
    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <span foreground="##ffffffaa">󰌾 Password</span>
    hide_input = false
    check_color = rgba(166, 227, 161, 0.8) # Soft Green
    fail_color = rgba(243, 139, 168, 0.8)  # Soft Red
    position = 0, -150
    halign = center
    valign = center
}

# ------------------------------------------------------------------------------
# MUSIC INFO (Song Details)
# ------------------------------------------------------------------------------
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/scripts/song-details.sh
    color = rgba(255, 255, 255, 0.60)
    font_size = 14
    font_family = $font
    position = 0, 40
    halign = center
    valign = bottom
}
