# Hyprpaper Wallpaper Configuration

wallpaper {
    monitor =
    path = /home/burakt/Pictures/Wallpapers/a_black_and_white_image_of_a_woman's_eyes.jpeg
    fit_mode = cover
}

# Enable IPC for live hyprctl hyprpaper commands
ipc = true

# Disable splash text rendering over the wallpaper
splash = false

