# Hyprsunset Configuration
# Blue light filter & gamma control

max-gamma = 150

# Gündüz profili — sabah 07:30'da normal ayarlara dön
profile {
    time = 7:30
    identity = true
}

# Gece profili — 21:00'de mavi ışık filtresi + hafif karartma
profile {
    time = 21:00
    temperature = 3000
    gamma = 0.85
}
